= Configure Files Generation
:toc:
:toc-placement!:

toc::[]

# Introduction

During the call to cmake it is possible to create files that use variables from
the CMakeLists.txt and cmake cache. During CMake generation the file is copied to a
new location and any cmake variables are replaced.(可以创建使用来自CMakeLists.txt和cmake cache(cmake内存)中的变量的文件。并且在CMake生成过程中，该文件被复制到新位置，并替换任何cmake变量)

The files in this tutorial are below:

```
$ tree
.
├── CMakeLists.txt
├── main.cpp
├── path.h.in
├── ver.h.in
```

  * link:CMakeLists.txt[] - Contains the CMake commands you wish to run
  * link:main.cpp[] - The source file with main
  * link:path.h.in[] - File to contain a path to the build directory
  * link:ver.h.in[] - File to contain the version of the project

# Concepts

## Configure Files

To do variable substitution in a file you can use the `configure_file()` function
in CMake. This core arguments for this function are source file and destination file.
（利用 `configure_file（）` 函数实现变量替换。其函数的核心参数是源文件和目标文件（说明路径）。该函数使用后，就可以在源文件里以 `${}` 或 `@@` 的形式使用在CMakeLists.txt里定义的变量。预处理时（猜测，因为即使在“”里都可以被替换），这些变量将会在目标文件里被替换成实际内容。）

[source,cmake]
----
configure_file(ver.h.in ${PROJECT_BINARY_DIR}/ver.h)

configure_file(path.h.in ${PROJECT_BINARY_DIR}/path.h @ONLY)
----

The first example above, allows the variable to be defined like a CMake variables using
the `${}` syntax or an `@@` in the ver.h.in file. After generation a new file ver.h will be available
in the `PROJECT_BINARY_DIR`.
（上面的第一个例子，源文件是ver.h.in，目标文件是ver.h(省略路径)，只做变量替换，其他内容不变。第二个例子有一个参数 @ONLY，意思是只识别带有 @@ 形式的变量。）

```
const char* ver = "${cf_example_VERSION}";
```

The second example, only allows variables to be defined using the `@@` syntax in the path.h.in file.
After generation a new file path.h will be available in the `PROJECT_BINARY_DIR`.

```
const char* path = "@CMAKE_SOURCE_DIR@";
```

# Building the Example

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/03-code-generation/configure-files/build

$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  path.h  ver.h

$ cat path.h
#ifndef __PATH_H__
#define __PATH_H__

// version variable that will be substituted by cmake
// This shows an example using the @ variable type
const char* path = "/home/matrim/workspace/cmake-examples/03-code-generation/configure-files";

#endif

$ cat ver.h
#ifndef __VER_H__
#define __VER_H__

// version variable that will be substituted by cmake
// This shows an example using the $ variable type
const char* ver = "0.2.1";

#endif

$ make
Scanning dependencies of target cf_example
[100%] Building CXX object CMakeFiles/cf_example.dir/main.cpp.o
Linking CXX executable cf_example
[100%] Built target cf_example

$ ./cf_example
Hello Version 0.2.1!
Path is /home/matrim/workspace/cmake-examples/03-code-generation/configure-files
----
