#!/bin/bash

# Required because cmake root isn't git root in this example
CLANG_FORMAT_BIN=$1
GIT_ROOT=`git rev-parse --show-toplevel`

pushd ${GIT_ROOT} > /dev/null

git status --porcelain \
	| egrep '*\.cpp|*\.h|*\.cxx|*\.hxx|*\.hpp|*\.cc' \
	| awk -F " " '{print $NF}' \
	| xargs -r ${CLANG_FORMAT_BIN} -style=file -output-replacements-xml \
	| grep "replacement offset" 2>&1 > /dev/null

RET=$?
popd > /dev/null

exit ${RET}
